"""add prompt_diagram + answer_format to exercise

Revision ID: 26d25dac90b4
Revises: 59516716c0c5
Create Date: 2026-06-18 00:01:52.727854
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '26d25dac90b4'
down_revision: Union[str, None] = '59516716c0c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('prompt_diagram', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('exercise', sa.Column('answer_format', sa.String(length=16), server_default='text', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'answer_format')
    op.drop_column('exercise', 'prompt_diagram')
    # ### end Alembic commands ###
