"""add summary to concept

Revision ID: 59516716c0c5
Revises: 5a6401873cdb
Create Date: 2026-06-17 19:31:29.449078
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59516716c0c5'
down_revision: Union[str, None] = '5a6401873cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('concept', sa.Column('summary', sa.Text(), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('concept', 'summary')
    # ### end Alembic commands ###
