"""add explanation to exercise

Revision ID: 5a6401873cdb
Revises: ae0bbbdef19b
Create Date: 2026-06-17 18:09:31.024076
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a6401873cdb'
down_revision: Union[str, None] = 'ae0bbbdef19b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise', sa.Column('explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercise', 'explanation')
    # ### end Alembic commands ###
