"""drop google auth fields (provider, avatar_url)

Revision ID: a63bd6ba2630
Revises: 26d25dac90b4
Create Date: 2026-06-25 08:32:30.039524
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a63bd6ba2630'
down_revision: Union[str, None] = '26d25dac90b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'avatar_url')
    op.drop_column('student', 'provider')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('provider', sa.VARCHAR(length=20), server_default=sa.text("'password'::character varying"), autoincrement=False, nullable=False))
    op.add_column('student', sa.Column('avatar_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
