"""add auth fields to student

Revision ID: ae0bbbdef19b
Revises: fb6ba43cd6e8
Create Date: 2026-06-15 19:34:54.262020
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae0bbbdef19b'
down_revision: Union[str, None] = 'fb6ba43cd6e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('password_hash', sa.String(length=200), nullable=True))
    op.add_column('student', sa.Column('avatar_url', sa.String(length=500), nullable=True))
    op.add_column('student', sa.Column('provider', sa.String(length=20), server_default='password', nullable=False))
    op.drop_constraint('student_email_key', 'student', type_='unique')
    op.create_index(op.f('ix_student_email'), 'student', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_student_email'), table_name='student')
    op.create_unique_constraint('student_email_key', 'student', ['email'])
    op.drop_column('student', 'provider')
    op.drop_column('student', 'avatar_url')
    op.drop_column('student', 'password_hash')
    # ### end Alembic commands ###
