"""initial schema

Revision ID: fb6ba43cd6e8
Revises: 
Create Date: 2026-06-04 09:58:20.017036
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fb6ba43cd6e8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('order_hint', sa.Integer(), nullable=False),
    sa.Column('explanation_md', sa.Text(), nullable=False),
    sa.Column('worked_example_md', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_concept_slug'), 'concept', ['slug'], unique=True)
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('chapter',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body_md', sa.Text(), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chapter_concept_id'), 'chapter', ['concept_id'], unique=False)
    op.create_table('concept_prerequisite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('prerequisite_concept_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ),
    sa.ForeignKeyConstraint(['prerequisite_concept_id'], ['concept.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('concept_id', 'prerequisite_concept_id', name='uq_concept_prereq')
    )
    op.create_index(op.f('ix_concept_prerequisite_concept_id'), 'concept_prerequisite', ['concept_id'], unique=False)
    op.create_index(op.f('ix_concept_prerequisite_prerequisite_concept_id'), 'concept_prerequisite', ['prerequisite_concept_id'], unique=False)
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('mcq', 'predict_output', 'pseudocode_order', name='exercise_type'), nullable=False),
    sa.Column('difficulty', sa.Enum('easy', 'medium', 'hard', name='difficulty'), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('correct_answer_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('target_misconception', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exercise_concept_id'), 'exercise', ['concept_id'], unique=False)
    op.create_table('mastery_estimate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('concept_id', sa.Integer(), nullable=False),
    sa.Column('p_mastered', sa.Float(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['concept_id'], ['concept.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'concept_id', name='uq_mastery_student_concept')
    )
    op.create_index(op.f('ix_mastery_estimate_concept_id'), 'mastery_estimate', ['concept_id'], unique=False)
    op.create_index(op.f('ix_mastery_estimate_student_id'), 'mastery_estimate', ['student_id'], unique=False)
    op.create_table('attempt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('response_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('misconception_label', sa.String(length=64), nullable=True),
    sa.Column('explanation_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_attempt_exercise_id'), 'attempt', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_attempt_student_id'), 'attempt', ['student_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_attempt_student_id'), table_name='attempt')
    op.drop_index(op.f('ix_attempt_exercise_id'), table_name='attempt')
    op.drop_table('attempt')
    op.drop_index(op.f('ix_mastery_estimate_student_id'), table_name='mastery_estimate')
    op.drop_index(op.f('ix_mastery_estimate_concept_id'), table_name='mastery_estimate')
    op.drop_table('mastery_estimate')
    op.drop_index(op.f('ix_exercise_concept_id'), table_name='exercise')
    op.drop_table('exercise')
    op.drop_index(op.f('ix_concept_prerequisite_prerequisite_concept_id'), table_name='concept_prerequisite')
    op.drop_index(op.f('ix_concept_prerequisite_concept_id'), table_name='concept_prerequisite')
    op.drop_table('concept_prerequisite')
    op.drop_index(op.f('ix_chapter_concept_id'), table_name='chapter')
    op.drop_table('chapter')
    op.drop_table('student')
    op.drop_index(op.f('ix_concept_slug'), table_name='concept')
    op.drop_table('concept')
    # ### end Alembic commands ###
